export const products = [
  {
    id: 1,
    url: "/list/digital-incense",
    image: "/products/1men.png",
    imageHover: "/products/1women.png",
    title: "digital incense",
    price: "45",
    desc: "Perfect mint green, organic material",
    cart: false,
  },
  {
    id: 2,
    url: "/list/wooden-chair",
    image: "/products/2men.png",
    imageHover: "/products/2women.png",
    title: "Wooden Chair",
    price: "15",
    desc: "Perfect mint green, organic material",
    cart: false,
  },
  {
    id: 3,
    url: "/list/white-tshirt",
    image: "/products/3men.png",
    imageHover: "/products/3women.png",
    title: "White Tshirt",
    price: "150",
    desc: "Perfect mint green, organic material",
    cart: false,
  },
  {
    id: 4,
    url: "/list/green-sweater",
    image: "/products/4men.png",
    imageHover: "/products/4women.png",
    title: "Green Sweater",
    price: "25",
    desc: "Perfect mint green, organic material",
    cart: false,
  },
];
